
const toggle=document.querySelector(".hamburger"),menu=document.querySelector(".menu");
if(toggle&&menu){toggle.addEventListener("click",()=>{const open=menu.classList.toggle("open");toggle.setAttribute("aria-expanded",open);document.body.classList.toggle("menu-open",open)});menu.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{menu.classList.remove("open");toggle.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open")}))}
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
document.querySelectorAll(".faq button").forEach(button=>button.addEventListener("click",()=>{const faq=button.closest(".faq"),answer=faq.querySelector(".faq-answer"),open=faq.classList.contains("open");document.querySelectorAll(".faq.open").forEach(other=>{if(other!==faq){other.classList.remove("open");other.querySelector(".faq-answer").style.maxHeight=null}});faq.classList.toggle("open",!open);answer.style.maxHeight=!open?answer.scrollHeight+"px":null}));
const topButton=document.querySelector(".top");if(topButton){window.addEventListener("scroll",()=>topButton.classList.toggle("visible",scrollY>650));topButton.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}))}
document.addEventListener("DOMContentLoaded",()=>{const banner=document.querySelector(".cookie"),accept=document.getElementById("acceptCookies"),key="allCleaningConsentAgencyV1";if(banner&&accept){if(localStorage.getItem(key)==="yes")banner.style.display="none";accept.addEventListener("click",()=>{localStorage.setItem(key,"yes");banner.style.display="none"})}});
const hero=document.querySelector(".hero-bg"),dots=document.querySelectorAll(".hero-dots button");
const heroImages=[
"https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=2000&q=88",
"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=2000&q=88",
"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=2000&q=88"];
let slide=0;function showSlide(i){if(!hero)return;slide=i;hero.style.opacity=.2;setTimeout(()=>{hero.style.backgroundImage=`url("${heroImages[i]}")`;hero.style.opacity=1},250);dots.forEach((d,n)=>d.classList.toggle("active",n===i))}
dots.forEach(d=>d.addEventListener("click",()=>showSlide(Number(d.dataset.slide))));if(hero&&dots.length)setInterval(()=>showSlide((slide+1)%heroImages.length),6000);
const lightbox=document.getElementById("lightbox");if(lightbox){const image=lightbox.querySelector("img"),close=lightbox.querySelector("button");document.querySelectorAll(".project img,.service img").forEach(img=>img.addEventListener("click",()=>{image.src=img.src;image.alt=img.alt;lightbox.classList.add("open")}));const shut=()=>lightbox.classList.remove("open");close.addEventListener("click",shut);lightbox.addEventListener("click",e=>{if(e.target===lightbox)shut()});document.addEventListener("keydown",e=>{if(e.key==="Escape")shut()})}
const quoteForm=document.getElementById("quoteForm"),message=document.getElementById("formMessage");
if(quoteForm&&message){quoteForm.addEventListener("submit",e=>{e.preventDefault();if(!quoteForm.checkValidity()){quoteForm.reportValidity();return}
const fd=new FormData(quoteForm);const subject=encodeURIComponent("Offerteaanvraag via website All Cleaning");const body=encodeURIComponent(`Naam: ${fd.get("naam")}\nBedrijf: ${fd.get("bedrijf")||""}\nE-mail: ${fd.get("email")}\nTelefoon: ${fd.get("telefoon")}\nDienst: ${fd.get("dienst")}\nGebouw: ${fd.get("gebouw")}\nFrequentie: ${fd.get("frequentie")||""}\n\nBericht:\n${fd.get("bericht")||""}`);message.textContent="Uw e-mailprogramma wordt geopend om de aanvraag te verzenden.";window.location.href=`mailto:info@all-cleaning.net?subject=${subject}&body=${body}`})}
